Folio_Test/Controllers/CoursesController.cs
using Folio_Test.DAL;
using Folio_Test.Model;
using Folio_Test.Repo;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Folio_Test.Controllers
{
    public class CoursesController : Controller
    {
       
        private IFolioDb db;

        public CoursesController()
        {
            db = new FolioContext();
        }

        public CoursesController(IFolioDb _db)
        {
            db = _db;
        }
            // GET: Courses
            public ActionResult Index()
        {
             return View(db.Query<Course>().ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            List<Course> listCourses = new List<Course>();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           Course  selectedcourse = db.Query<Course>().Single(r => r.CourseID == id);
            listCourses.Add(selectedcourse);
            Session["CourseTitle"] = selectedcourse.CourseTitle;
            Session["CourseID"] = selectedcourse.CourseID;
            Session["Course"] = listCourses;
            if (selectedcourse == null)
            {
                return HttpNotFound();
            }


            if (Request.IsAjaxRequest())
            {
         
                return PartialView("_studentPartialView",Session["Course"] as List<Course> );
            }
            else
            { return View(selectedcourse); }


        }
      
        // GET: Courses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseID,CourseTitle,Location,TeacherName")] Course course)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Add(course);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View(course);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Query<Course>().Single(r => r.CourseID == id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseID,CourseTitle,Location,TeacherName")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Update(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course =  db.Query<Course>().Single(r => r.CourseID == id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Query<Course>().Single(r => r.CourseID == id);
            db.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Folio_Test/Controllers/StudentsController.cs
using Folio_Test.BusinessLogic;
using Folio_Test.DAL;
using Folio_Test.Model;
using Folio_Test.Repo;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Folio_Test.Controllers
{
    public class StudentsController : Controller
    {
        private IFolioDb db ;

        public StudentsController()
        {
            db = new FolioContext();
        }

        public StudentsController(IFolioDb _db)
        {
            db = _db;
        }
  

        // GET: Students
        public ActionResult Index()
        {
            return View(db.Query<Student>().ToList());
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Query<Student>().Single(r => r.ID == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            if (Session.Keys.Count != 0)
            { ViewBag.Title = Session["CourseTitle"].ToString();}
            return View();
        }

        // POST: Students/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,LastName,FirstMidName,EnrollmentDate,Gpa,Age")] Student student)
        {
            int courseId = 0; bool enrollmentBit = false; var enrollment = new Enrollment();

            if (Session.Keys.Count != 0)
            {
                ViewBag.Title = Session["CourseTitle"].ToString();
                enrollmentBit = int.TryParse(Session["CourseID"].ToString(), out courseId);
            }
            try
            {
               if(Constraints.SurName_Uniqueness(student))
                {
                   ModelState.AddModelError("", "Student Already exists with same Surname");
                }
                if (ModelState.IsValid)
                {
                    db.Add(student);
                    db.SaveChanges();

                    if (enrollmentBit)
                    {
                        enrollment = new Enrollment { CourseID = courseId, StudentID = student.ID };
                        db.Add(enrollment);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Query<Student>().Single(r => r.ID == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,LastName,FirstMidName,EnrollmentDate,Gpa,Age")] Student student)
        {
            try
            {
           
            if (ModelState.IsValid)
            {
                db.Update(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Query<Student>().Single(r => r.ID == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Query<Student>().Single(r => r.ID == id);
            db.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Folio_Test/Views/Courses/Create.cshtml
@model Folio_Test.Model.Course

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
          @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Folio_Test/Views/Courses/Delete.cshtml
@model Folio_Test.Model.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Folio_Test/Views/Courses/Details.cshtml
@model Folio_Test.Model.Course

@{
    ViewBag.Title = Model.CourseTitle;
}
<h2>@ViewBag.Title</h2>

<div>
    <dl class="dl-horizontal">
        <dd>
            <table class="table">
                <tr>
                    <th>Student Name</th>
                    <th>Age</th>
                    <th>GPA</th>
                </tr>
                @foreach (var item in Model.Enrollments)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Student.StudentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Student.Age)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Student.Gpa)
                        </td>
                        <td>

                            @Html.ActionLink("Edit", "Edit", "Students", new { item.Student.ID }, null) |
                            @Html.ActionLink("Delete", "Delete", "Students", new { id = item.Student.ID }, null)
                        </td>
                    </tr>
                }
                <tr>
                    <td>
                        <p>
                            @Html.ActionLink("ADD", "Create", "Students", @"ViewBag.Title", null)
                        </p>
                    </td>
                </tr>
            </table>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CourseID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Folio_Test/Views/Courses/Edit.cshtml
@model Folio_Test.Model.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CourseID)

        <div class="form-group">
            @Html.LabelFor(model => model.CourseTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Folio_Test/Views/Courses/Index.cshtml
@model IEnumerable<Folio_Test.Model.Course>

@{
    ViewBag.Title = "Classes";
}

<h2>@ViewBag.Title</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CourseTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeacherName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>

                @Ajax.ActionLink(item.CourseTitle,"Details","Courses",new { id= item.CourseID },
        new AjaxOptions()
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            AllowCache = false,
            UpdateTargetId = "enrolledStudents",
            OnBegin= " HighLightRowsGpaThreeGreater('studentList', 3, 3.0)",
            OnSuccess = " HighLightRowsGpaThreeGreater('studentList', 3, 3.0)"
        })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeacherName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CourseID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CourseID })
            </td>
        </tr>

    }
    <tr>
        <td>
            <p>
                @Html.ActionLink("ADD", "Create")
            </p>
        </td>
    </tr>
</table>

@Html.Partial("_studentPartialView", Session["Course"] as List<Folio_Test.Model.Course>)

@Scripts.Render("~/bundles/FolioOne")

<script type="text/javascript">

    $(document).ready(function () {
        HighLightRowsGpaThreeGreater('studentList', 3, 3.0);
    });

    function HighLightRowsGpaThreeGreater(gridviewID, columnIndex, value) {
        $("#" + gridviewID + " td:nth-child(" + columnIndex + ")").each(function () {
            if (parseInt($(this).text()) >= value) {
                $(this).parent("tr").css("background-color", "Lavender ");
            }
        });
    }
</script>

Folio_Test/Views/Courses/_studentPartialView.cshtml
@model  IEnumerable<Folio_Test.Model.Course>

@{
    ViewBag.Title = Session["CourseTitle"];
}
<h2>@ViewBag.Title </h2>

<div id="enrolledStudents">
    <dl class="dl-horizontal">
        <dd>
            <table class="table" id="studentList">
                <tr>
                    <th>Student Name</th>
                    <th>Age</th>
                    <th>GPA</th>
                </tr>
                @foreach (var item in Model)
                {
                    foreach (var item1 in item.Enrollments)
                    {

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item1.Student.StudentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item1.Student.Age)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item1.Student.Gpa)
                        </td>
                        <td>

                            @Html.ActionLink("Edit", "Edit", "Students", new { item1.Student.ID }, null) |
                            @Html.ActionLink("Delete", "Delete", "Students", new { id = item1.Student.ID }, null)
                        </td>
                    </tr>
                    }
                }
                <tr>
                    <td>
                        <p>
                            @Html.ActionLink("ADD", "Create", "Students", @"ViewBag.Title", null)
                        </p>
                    </td>
                </tr>
            </table>
        </dd>

    </dl>
</div>